### PR TITLE
[UPD] anuncioslumicolor: Update mexico and vendor-bills submodules

### PR DESCRIPTION
**Pull request by rolandojduartem**

### CODE REVIEW

**Comment by rolandojduartem** [comment]
@hugho-ad Done!

**Comment by hugho-ad** [comment]
@luistorresm 

could you review pls

**Comment by rolandojduartem** [comment]
@EvelynMoraCastro, may you do the functional review of this update on odoo.sh.

cc @hugho-ad

**Comment by hugho-ad** [comment]
friendly reminder @luistorresm

**Comment by rolandojduartem** [comment]
Hi, @EvelynMoraCastro, may you do the functional review of this update on odoo.sh.

cc @hugho-ad

**Pull request closed without merging**
